# 主要数据页索引
- name: Cup1
  link: /InnovationClassGroup8
- name: Cup2
  link: /InnovationClassGroup8/about.html
- name: Cup3
  link: /InnovationClassGroup8/blog.html
- name: Cup4
  link: /InnovationClassGroup8/staff.html
- name: Cup5
  link: /InnovationClassGroup8/resume.html